name: Enviar reporte de combustibles diario

on:
  schedule:
    - cron: '0 14 * * *'  # 14:00 UTC = 8:00 AM CDMX
  workflow_dispatch:

jobs:
  enviar-reporte:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Instalar dependencias
        run: npm install

      - name: Ejecutar script
        env:
          GMAIL_USER: ${{ secrets.GMAIL_USER }}
          GMAIL_PASS: ${{ secrets.GMAIL_PASS }}
        run: node index.js
